package com.myapps.mkain.dccharacters.util;

import com.myapps.mkain.dccharacters.R;
import com.myapps.mkain.dccharacters.model.Character;
import com.myapps.mkain.dccharacters.dao.CharacterDao;

public class Resource {

    public static void init() {
        CharacterDao.getInstance().save(new Character("Batman", "Bruce Wayne", "Dark Knight. Caped Crusader. World’s Greatest Detective. Whatever you know him as, wherever you know him from—the blockbuster movies, TV shows, video games, cartoons, or millions of comics—Batman is proof you don’t need superpowers to be a superhero… and the poster boy for what a bad childhood can do to you.", "Millionaire Bruce Wayne was just a kid when he watched his parents get gunned down during a mugging in Gotham City. The crime would define his life, as he dedicated himself to becoming the world’s greatest weapon against crime—the Batman.\n" +
                "\n" +
                "Forget his Batarangs, Batmobile, or Utility Belt filled with high-tech weapons. Batman is the most feared superhero of all, because he’s pushed himself to the absolute pinnacle of human achievement. He’s a brilliant detective who’s mastered fighting techniques the world’s barely heard of. An Olympic-caliber athlete with a plan for every occasion, Batman’s seemingly always five steps ahead of his foes. But in his crusade against injustice, two questions always loom: How far will he go to protect the innocent, and will he sacrifice his humanity along the way?", R.drawable.char_215x215_batman));
        CharacterDao.getInstance().save(new Character("Superman", "Kal-El, Clark Joseph Kent", "Look! Up in the sky! It’s a bird! It’s a plane! It’s…Well, you know how it ends, don’t you? It’s a sentence so iconic, there are probably kids shouting it in Swahili as you read this.", "The most recognized superhero in pop culture, Superman has been elevated to mythic folkhero status. Rocketed to Earth from the dying planet Krypton, baby Kal-El was found by a farming couple who named the boy Clark Kent and raised him as their own. Discovering his enormous powers, they instilled in him strong moral values—and inspired him to become a hero.\n" +
                "\n" +
                "Superman has super-everything—strength, speed, flight, invulnerability as well as his renowned X-ray and heat vision. The most powerful being on the planet, his amazing abilities are also a melancholy reminder of how different he is from the people he’s dedicated to protect. \n" +
                "\n" +
                "A universal icon, Superman means different things to the many diverse people he inspires: He’s an alien; an immigrant from a faraway land just looking to help; a country boy fighting the never-ending battle for truth and justice. And recent comics have truly spotlighted his role as the people’s hero: Following a neophyte Man of Steel still learning his powers’ limits, Superman fights the evil corporate tycoons and corrupt one-percenters that have overwhelmed the establishment.",  R.drawable.char_215x215_superman));
        CharacterDao.getInstance().save(new Character("Green Lantern", "Hal Jordan", "Imagine if the ring on your finger was more than a piece of gaudy jewelry. Instead, it’s the universe’s most powerful weapon. It can create whatever you wish out of pure energy, its might limited only by your imagination and will. And with it comes exclusive membership to an exclusive intergalactic police force with alien officers spanning the cosmos.", "The only catch? Mastering that power and being a Green Lantern means facing your fears, and for headstrong Hal Jordan, that’s something he’s been avoiding his whole life.When just a boy, Hal witnessed his greatest nightmare—his pilot father dying in a tragic plane crash. Nevertheless determined to follow in his footsteps, Hal repressed his fears, becoming a reckless, defiant test pilot. But when a dying alien crashes on Earth, the irresponsible Hal is chosen to be that alien’s successor in the Green Lantern Corps, a universe-wide peacekeeping force over 3,600 members strong.\n" +
                "\n" +
                "And his life only gets wilder from there. Alien romances. Intergalactic wars. Power-hungry super-villains. Wielding a Green Lantern power ring—a weapon fueled by willpower—he can fly and create constructs made of pure energy, generating anything from massive green fists to emerald rifles that can snipe from a planet away. But while Hal tends to ignore his fears, he’ll learn the only way to truly master his ring’s power is by confronting and overcoming them.", R.drawable.char_215x215_greenlantern));
        CharacterDao.getInstance().save(new Character("Wonder Woman", "Diana", "OK, let’s just come out and say it: Wonder Woman is the most famous heroine of all time. No offense to the Lara Crofts, Buffys, or Disney princesses of the world, but none of them have been plastered on as many magazine covers, adorned as many T-shirts, or sold the countless comics, dolls, and action figures that Wonder Woman has. The full package of beauty, brains, and brawn, she’s been a feminist icon since her star-spangled intro in 1941.", "Wonder Woman is Princess Diana of the immortal Amazons from Greek mythology.  When army pilot Steve Trevor crashes on the warriors’ secluded island paradise, Diana wins the right to escort him home and make her people known to the world. Entering our cynical world for the first time, there’s a lot she must wrap her head around, especially our ways of war, hate, and, well… dating. Helping her are her superhuman strength and speed, as well as the trademark bulletproof bracelets, but it’s probably her Golden Lasso of Truth most people really wish they had.\n" +
                "\n" +
                "Torn between a mission to promote peace and her own warrior upbringing, Wonder Woman fights evil while hoping to unlock the potential of a humanity she doesn’t always understand.", R.drawable.char_215x215_wonderwoman));
        CharacterDao.getInstance().save(new Character("Aquaman", "Arthur Curry", "Make all the sushi jokes, YouTube spoofs, and SNL sketches you want, Aquaman’s been an icon for over seventy years. The King of the Seven Seas. Reluctant ruler of Atlantis. A man who holds his own against heroes like Superman and Wonder Woman. He’s so recognizable that when officials speak about the perils of sea pollution, they’ll whip out Aquaman references to sound hip.", "Cast out from Atlantis as a baby, Arthur Curry grew up on land, thinking himself a normal human. But when he matured, Atlantis returned, claiming him as their rightful king. Caught between a surface world constantly ravaging the sea and Atlanteans looking to lash out in revolt, he’s committed to protecting the entire globe.\n" +
                "\n" +
                "Aquaman is the king of all things aqua. He can breathe underwater, swim at tremendous speeds, and telepathically communicate with sea life. Being able to withstand ocean depths, he gets bonus points on land with his superhuman strength, enhanced senses, and nearly impenetrable skin. And although his courage and decisive nature have proven him a true heir to Atlantis’s throne, the continual conflict between land and sea makes him a citizen of both—and at home in neither.", R.drawable.char_215x215_aquaman));
        CharacterDao.getInstance().save(new Character("Flash", "Barry Allen", "Indy cars, bullet trains, supersonic aircraft… The Flash leaves them all in the dust.", "Young Barry Allen’s life stopped the minute his mother was murdered. The true killer never found, its mystery obsessed Barry, driving him to become a forensic scientist. Consumed by his work, he spent his life chained to his desk, solving every case that flew across it. But when a freak lightning bolt hits a nearby shelf in his lab, Barry receives super-speed, becoming the Flash. Now, he’ll race up buildings, across oceans, and around the world to get his man—while getting introduced to a world so much bigger than his old life of microscopes and cold cases.\n" +
                "\n" +
                "Explore some of The Flash’s greatest adventures through the years.Able to run at near light-speeds, his powers provide the ultimate caffeine kick: He can run up buildings, move so swiftly he phases through objects, create sonic booms with the snap of his fingers—and never need to order delivery. Despite his speed, Barry can become so obsessed with crime-solving he can still lose track of everything else around him, leaving the fastest man alive constantly running a minute behind.", R.drawable.char_215x215_flash));
    }
}
